### ISSUE TITLE
Repository todo tracker

### ISSUE THREAD

**Issue by patrickcping** [patrickcping/pingone-go-sdk-v2#1]
### Management

- [ ] **ActiveIdentityCounts** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/181
- [ ] **Activities** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/182
- [x] **Agreements** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/158
- [x] **AlertChannels** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/159
- [ ] **ApplicationSignons** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/160
- [x] **BrandingSettings** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/161
- [ ] **Capabilities** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/162
- [x] **Certificates** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/163
- [x] **CustomDomains** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/164
- [ ] **Decryptions** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/165
- [x] **DeviceAuthenticationPolicy** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/166
- [x] **EmailDomains** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/167
- [ ] **Encryptions** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/168
- [x] **IdentityProviders** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/169
- [ ] **Integrations** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/170
- [x] **Keys** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/171
- [x] **Languages** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/172
- [ ] **MetricsActiveIdentityCounts** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/192
- [ ] **NotificationsSettings** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/173
- [ ] **Propagation** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/174
- [ ] **Signings** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/175
- [x] **Subscriptions** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/176
- [ ] **Templates** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/177
- [x] **Themes** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/178
- [ ] **TotalIdentities** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/180
- [ ] **UserActivities** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/179
- [ ] **Users** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/183
- [ ] **Verifications** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/184

### MFA

- [x] **DeviceAuthenticationPolicy** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/187
- [x] **MfaSettings** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/188
- [ ] **Users/Devices** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/189
- [ ] **Users/MfaEnabled** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/190
- [ ] **Users/PairingKeys** - depends on https://github.com/patrickcping/pingone-openapi-specs/issues/191

### Risk
n/a

## CI
- [x] Build validation CI
- [ ] patrickcping/pingone-openapi-specs#156
- [ ] Codegen validation CI
- [ ] Changelog build process
- [ ] Release/tagging process

## Documentation
- [ ] Getting started
- [ ] Contributing guide
- [ ] Changelog process
- [ ] PR checklist

## Contribution
- [ ] Issue template
- [ ] PR template
